### ISSUE TITLE
LiveTV Folder is empty, no channels or shows / movies

### ISSUE THREAD

**Issue by FritLP** [jellyfin/jellyfin-vue#2398] opened 2024-07-07 00:17 UTC
### Description of the bug

My LiveTV folder does not show the channels or any series / movies etc., as you can see in the following picture :o

![image](https://github.com/jellyfin/jellyfin-vue/assets/93882479/cd09b4ea-0422-40e1-8fc7-7dd051dd524d)

### Steps to reproduce

I only had a nromal LiveTV with an m3u and an xml for the epg. In the normal WEB Client everything works fine.

### Expected behavior

It was nice to see the channels, series, movies, epg. Like in the normal web client :D

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.9.7

**Comment by ferferga** [comment] 2024-07-07 08:39
@FritLP Hello! First of all, you're using an ancient commit from December 2021, so probably you should check into setting up Watchtower or some automated means for updating your Docker container (or reverse proxy the hosted instance in case you're not using Docker). I know that's part of my fault because the deployment documentation doesn't exist yet.

As for Live TV support, it doesn't exist yet, it's on the roadmap and it's a duplicate of #1848
I don't use Live TV myself, but it looks like in recent versions you can at least have a listing but without channels. Please update the former issue accordingly in case that's not the current case, that helps me understand better the current state of the feature.

**Closed by ferferga** 2024-07-07 08:39 UTC
Labels: bug
