### ISSUE TITLE
Visible scrollbars during video playback

### ISSUE THREAD

**Issue by sfkpmr** [jellyfin/jellyfin-vue#1773] opened 2022-06-11 06:41 UTC
### Description of the bug

When starting playback of video in Chromium, the side scrollbar remains visible, and a bottom scrollbar appears.

![image](https://user-images.githubusercontent.com/10453979/173176536-934eb13a-4458-4c33-bcad-89fba9261892.png)

In Firefox the side scrollbar remains visible, but the bottom one doesn't appear.

Vue 8a4f36e
Firefox 101.0
Chromium 102.0.5005.61
Fedora (KDE Plasma)

### Steps to reproduce

Start playback of video.

### Expected behavior

No visible sidebars during video playback.

### Platform

Linux

### Browser

Other (Please specify in the "additional context" section)

### Jellyfin server version

10.8.0

**Comment by ldexterldesign** [comment] 2022-06-26 21:48
Same

```
Vivaldi | 5.3.2679.51 (Stable channel) (x86_64)
-- | --
Revision | 6e449a1e01d22b5335622ea66ec339c84b860b08
OS | macOS Version 12.4 (Build 21F79)
JavaScript | V8 10.2.154.8
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.108 Safari/537.36
Command Line | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --flag-switches-begin --flag-switches-end --disable-smooth-scrolling --save-page-as-mhtml
Executable Path | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path | /Users/ldexterldesign/Library/Application Support/Vivaldi/Default
Linker | lld
```

**Comment by Vankerkom** [comment] 2022-11-10 18:54
The horizontal scrollbar is caused by incorrect use of `width: 100vw`. A fix for this is on it's way.

The vertical scrollbar is the regular scrollbar for the application. This is correct browser behaviour because the video player is being displayed inside a full-screen pop-up.

**Comment by ferferga** [comment] 2022-11-15 18:07
Left scrollbar is still visible

**Closed** 2023-04-03 10:53 UTC
Labels: bug, confirmed
