### ISSUE TITLE
Arrow keys controlling music playback

### ISSUE THREAD

**Issue by neopc10** [jellyfin/jellyfin-vue#971] opened 2021-04-06 14:58 UTC
Currently the left and right arrow keys will go to the previous and next song queued on the fullscreen music player or anywhere the bottom controls are visible.

Also currently the left and right arrow keys (in addition to pg up+down) will go to the previous and next swiper pages on the home screen.

They shouldn't do both simultaneously -- I think the best would be to enable left/right arrow keys for music controls only in the fullscreen music player.

**Comment by ferferga** [comment] 2021-04-06 15:04
This is probably a side effect of using ``keep-alive``.

Should be fixed once the player is in its own layout (which is planned once we switch to Vue 3) but maybe I can hack a temporary solution.

**Comment by ferferga** [comment] 2021-04-06 15:07
Although it's not intended, I don't see anything wrong in the behaviour: it's not like we will have places where you would need to use those controls for something else and they may overlap.

Why do you think this should be fixed? And what's your opinion on this?

@MrTimscampi @dkanada @ThibaultNocchi @Camc314

**Comment by neopc10** [comment] 2021-04-06 15:11
I find myself using the arrow keys rather than the mouse to navigate through the home screen. Naturally, the left and right arrow keys to scroll through the top swiper. If I'm listening to something while navigating through the library view (swiper included), I'll instantly lose my place on the track I'm listening to as I just skipped it.

In the fullscreen music player, I'm clearly not navigating anywhere. Any arrow inputs are clearly meant to control playback.

**Comment by MrTimscampi** [comment] 2021-04-06 15:12
> This is probably a side effect of using `keep-alive`.

It's not, it's due to this: https://github.com/jellyfin/jellyfin-vue/blob/master/client/components/Players/PlayerManager.vue#L403-L418

The issue is the entire video player UI (and logic) living inside PlayerManager. I'm planning to move it, but only after #961 is merged, because doing both at the same time would be very annoying for reviews and rebases.

Also planned is merging AudioPlayer and VideoPlayer into a generic ShakaPlayer, since they're mostly identical.

> Although it's not intended, I don't see anything wrong in the behaviour: it's not like we will have places where you would need to use those controls for something else and they may overlap.

I don't agree, only video should have keybindings. Music should rely on the browsers MediaSessions API stuff for control.

**Closed** 2022-05-02 08:06 UTC
Labels: bug, confirmed
