### ISSUE TITLE
The collections do not contain the items

### ISSUE THREAD

**Issue by doc-code-hub** [jellyfin/jellyfin-vue#1671] opened 2022-01-06 19:02 UTC
### Description of the bug

![image](https://user-images.githubusercontent.com/61033694/148436260-af5f1bf9-a662-4283-b432-1036a0d33aac.png)

Where are the titles in the collections?

From the original website, I set up the films page to group the films in collections.
This means that in my movie list, all of those in a collection are not visible (outside of the collection itself).

But when I open a collection, I don't see any of the items that belong to it. Instead I only see suggestions of similar collections ...

The only way I have to see those contents is to search for them from the search bar or reproduce (at random) the collection, and view the single elements from the queue, during playback.

I believe that as in the original site, in the page of a collection you should be able to view the elements that belong to it (among the various types: series, films, etc).

### Steps to reproduce

- Create a collection
- Put some films in that collection
- Set this option (In Admin Dashboard > Library > Display tab, from the original site)
![image](https://user-images.githubusercontent.com/61033694/148435084-e4cb671e-daed-421b-9503-80d54008e4ae.png)
- From the Vue App, go to that collection

You shouldn't see any of the titles you added on that page

### Expected behavior

The collections page should contain the elements that belong to it, divided by type.

For example as in the photo taken from the original site
![image](https://user-images.githubusercontent.com/61033694/148436095-f249fa41-6830-4a95-b204-1ecab113842d.png)

### Platform

Windows

### Browser

Chrome

### Jellyfin server version

10.7.7

### Additional context

```text
I deployed with the provided Dockerfile on the same server running Jellyfin 10.7.7
```

**Comment by ferferga** [comment] 2022-01-06 20:46
Hello! This is a duplicate of #760
This is not implemented yet as this is still an experimental client and its a continuous work in progress.

Closing this in favor of the aforementioned PR

**Closed** 2022-01-06 20:46 UTC
Labels: bug
