### ISSUE TITLE
Remaining episodes counter doesn't update

### ISSUE THREAD

**Issue by LPkkjHD** [jellyfin/jellyfin-vue#1717] opened 2022-02-15 06:42 UTC
### Description of the bug

When in an overview of a library which is marked as TV-Shows there's the option to mark entire seasons as watched.
However doing so doesn't update the view but rather only calls the route.

Manually refreshing the page is required to display the changes made.

### Steps to reproduce

In a TV-Shows marked library overview:
- find a show with at least 1 unseen episode
- click on the tick button in the overview
- nothing happens until you refresh the page manually or navigate away and back to it again

### Expected behavior

Pill with the remaining episodes is updated as soon as the call to the server is successful.

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.7.7

**Comment by LPkkjHD** [comment] 2022-02-15 07:40
After a bit of digging it seems that we don't subscribe to changes in the `item.UserData` object which are done by nested components (in our case the `mark-played-button`) in [`components/Item/Card/Card.vue`](https://github.com/jellyfin/jellyfin-vue/blob/master/src/components/Item/Card/Card.vue).

**Comment by ferferga** [comment] 2024-01-08 18:15
@LPkkjHD Hello! Can you please check if #2201 fixes the issue for you? There will always be a deployment link in the PR.

Feedback is much appreciated.

**Comment by LPkkjHD** [comment] 2024-01-08 20:14
Thank you for getting back on this one. Unfortunately this does not fix the issue as of #2201 with the most recent deployment.

**Comment by ferferga** [comment] 2024-01-08 21:41
@LPkkjHD Can you please give me more detailed reproduction steps? I can't reproduce


https://github.com/jellyfin/jellyfin-vue/assets/10274099/7857cb40-fdd8-47c4-8e4b-50254c7231ef

**Comment by LPkkjHD** [comment] 2024-01-09 20:20
Now that I see your video I think my description of this issue is not quite accurate. I was noticing the Issue at hand during the "library" view.
Anyhow, I tested this again (this time against a 10.8.13 Server) and I can't reproduce your behaviour.


https://github.com/jellyfin/jellyfin-vue/assets/11832982/441a230c-2f53-4edc-bc47-a1d15d93a0e4


https://github.com/jellyfin/jellyfin-vue/assets/11832982/99d1b8f4-0374-435a-847b-2779eaa116e4

**Comment by ferferga** [comment] 2024-01-10 09:07
@LPkkjHD I merged the PR to have playback working again in master asap. Although the issue was closed automatically, count on me to keep troubleshooting, but this no longer *should* be a Vue issue (unless there's an issue in the way we get updates from the server or the server is sending incorrect updates)

**Closed** 2024-01-10 09:07 UTC
Labels: bug

**Comment by LPkkjHD** [comment] 2024-01-10 16:35
@ferferga the behaviour you've shown is the correct one.

> Did you see any error message about not having Internet connection at any point while browsing? 
This did not occur.

> It happens the same with favoriting?
Favouriting shows works instantly

> Open an item side to side with Web. If you favorite an item in Vue, does it replicate instantly in Web? (It should)
This works as expected

I'm going to dig into my reverse proxy settings. Maybe I'll find something

**Comment by ferferga** [comment] 2024-03-17 12:31
@LPkkjHD I found the probable issue you were facing: https://github.com/vueuse/vueuse/pull/3870

After login, the socket was not being connected because it did not react to the ``socketUrl`` ref update, so it only connected if you started the client when being logged in.

The above PR will fix the issue upstream.
