### ISSUE TITLE
Default server url does not work

### ISSUE THREAD

**Issue by kimboslice99** [jellyfin/jellyfin-vue#2176] opened 2023-12-29 02:53 UTC
### Description of the bug

Client is setup on a subdomain and pointed to the other subdomain with jellyfin running on it, the config.json is set with defaultServerURLs containing jellyfins subdomain

The client will make 4 requests for /System/Info/Public

 the first it makes is to jellyfin.domain.tld:8096/System/Info/Public
 the next one it is successful, it obtains the server info, then it proceeds to try twice more anyways
 
 3rd time it trys port 8920? - why?
 4th it then trys with http when were on a https page
 
 And at the end of it all, it still complains `server not found`
 
 So, why are we not respecting the config? and why, after a successful attempt, do we keep trying anyways?
 
 Am I missing something? seems like defaultServerURLs is not effective at doing its job whatsoever

### Steps to reproduce

.

### Expected behavior

.

### Platform

Windows

### Browser

Edge

### Jellyfin server version

10.8.13

**Comment by kimboslice99** [comment] 2023-12-29 05:21
Ok so heres whats happening via devtools->application->local storage

Load page-> auth key doesnt contain server information, Add server prompt is shown

It takes 3-4 seconds before the auth storage key is updated, at which point the login prompt will be shown if reloaded (without path)

I would much rather see this login prompt shown immediately on first load, one would hope thats the point of the `defaultServerURLs` setting, this setting should be used directly by the client, but seems like its more of an instruction to the client to try all servers in the list plus variations like 8920 and 8096.

**Comment by kimboslice99** [comment] 2023-12-29 07:17
For others reading, heres a quick and dirty way to get this behavior

Load jellyfin-vue and do not log in, just wait for the auth key to populate then grab the value of the key and use it here

```
  <script>
	localStorage.setItem('auth', 'enter_key_info');
  </script>
```
Place this in index.html before any other script tag, jellyfin-vue will now load straight to a login prompt

**Comment by ferferga** [comment] 2023-12-29 19:38
Duplicate of #2117

**Closed by ferferga** 2023-12-29 19:38 UTC
Labels: bug

**Comment by kimboslice99** [comment] 2023-12-29 19:48
Thought I had checked pretty thoroughly but guess I missed that one

**Comment by kimboslice99** [comment] 2023-12-29 20:12
not planned? defaultServerURLs **needs** to be directly used by the client, this function of "try all possible ports associated with x domain" has got to be the worst way this could be done, use the port specified in the url, if any.

**Comment by ferferga** [comment] 2023-12-29 21:03
That's a GitHub default message, because it's the most fitting category for closing a duplicate issue. 

The attempted ports doesn't have anything to do with this client and it's a default check that happens at the SDK level (I believe Web also does it), it probes for server, it appearing as an error in the console doesn't mean it's a real error of the application. There's no way it can be hidden.

The real issue here it's the one linked and the wiki typo (which I will fix shortly), this is still 100% a duplicate.

**Comment by ferferga** [comment] 2023-12-30 17:39
@kimboslice99 Just reviewing what you said about the typo of the wiki, I can't find the typo, where is it?

**Comment by kimboslice99** [comment] 2023-12-30 23:25
> @kimboslice99 Just reviewing what you said about the typo of the wiki, I can't find the typo, where is it?

Under non-docker based setups

**Comment by ferferga** [comment] 2023-12-30 23:40
@kimboslice99 Found, thank you very much!
